// Karaman merkez mahalleleri (emlak ilanları için kullanılır)
// Hem anasayfadaki filtrede hem admin panelindeki ilan formunda kullanılır.

export const KARAMAN_MAHALLELERI = [
  'Abbas Mahallesi',
  'Ahiosman Mahallesi',
  'Ahmet Yesevi Mahallesi',
  'Alişahane Mahallesi',
  'Atatürk Mahallesi',
  'Bahçelievler Mahallesi',
  'Beyazkent Mahallesi',
  'Cedit Mahallesi',
  'Cumhuriyet Mahallesi',
  'Elmaşehir Mahallesi',
  'Fatih Mahallesi',
  'Fenari Mahallesi',
  'Gazidükkan Mahallesi',
  'Hacıcelal Mahallesi',
  'Hisar Mahallesi',
  'Hürriyet Mahallesi',
  'Ibrahim Hakkı Konyalı Mahallesi',
  'Imaret Mahallesi',
  'Karamanoğlu Mehmet Bey Mahallesi',
  'Külhan Mahallesi',
  'Larende Mahallesi',
  'Mahmudiye Mahallesi',
  'Mansurdede Mahallesi',
  'Mehmet Akif Ersoy Mahallesi',
  'Mümine Hatun Mahallesi',
  'Nefise Sultan Mahallesi',
  'Osmangazi Mahallesi',
  'Sakabaşı Mahallesi',
  'Sekiçeşme Mahallesi',
  'Şeyh Şamil Mahallesi',
  'Siyahser Mahallesi',
  'Sümer Mahallesi',
  'Tabduk Emre Mahallesi',
  'Topucak Mahallesi',
  'Urgan Mahallesi',
  'Valide Sultan Mahallesi',
  'Yenimahalle Mahallesi',
  'Ziya Gökalp Mahallesi',
];